name: latte
description: "Listen Music With Latte"
publish_to: "none"
version: 1.0.3+7

environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  flutter_bloc:
  bloc:
  rxdart:
  equatable:
  dio:

  youtube_explode_dart: ^2.1.0
  cupertino_icons: ^1.0.6

  just_audio:
  just_audio_mpv:
  just_audio_background: any
  audio_video_progress_bar: ^2.0.2

  sliding_up_panel: ^2.0.0+1

  hive_flutter:
  hive_generator: ^2.0.1
  flutter_slidable: ^3.1.0

  flutter_launcher_icons:
  melon:
    git:
      url: "https://github.com/dev-hann/melon.git"
      ref: "main"

  go_router:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner:

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  ios: true
  android: true
flutter:
  assets:
    - shorebird.yaml
  uses-material-design: true
