name: latte
description: "Listen Music With Latte"
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  flutter_bloc:
  bloc:
  rxdart:
  equatable:

  youtube_explode_dart: ^2.1.0
  cupertino_icons: ^1.0.6

  just_audio:
  just_audio_mpv:
  just_audio_background: any

  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - shorebird.yaml
  uses-material-design: true
